/**
 * Seed configuration for the Media Data Harmonization Workbench.
 * Hierarchies, mapping dictionary, and synonym trees are the source of truth.
 * Column synonym keys align with config/target_template.json + config/synonyms.json.
 */
window.HW_SEED = {
  standardFields: [
    { id: "date", label: "Date", type: "date", mandatory: true },
    { id: "publisher", label: "Publisher", type: "dimension", mandatory: true },
    { id: "channel", label: "Channel", type: "dimension", mandatory: true },
    { id: "country", label: "Country", type: "dimension", mandatory: true },
    { id: "category", label: "Category", type: "dimension", mandatory: true },
    { id: "brand", label: "Brand", type: "dimension", mandatory: true },
    { id: "brand_family", label: "Brand Family", type: "dimension", mandatory: false },
    { id: "advertiser", label: "Advertiser", type: "hierarchy", mandatory: false },
    { id: "campaign", label: "Campaign", type: "hierarchy", mandatory: true },
    { id: "campaign_type", label: "Campaign Type", type: "dimension", mandatory: false },
    { id: "campaign_objective", label: "Campaign Objective", type: "dimension", mandatory: false },
    { id: "insertion_order", label: "Insertion Order", type: "hierarchy", mandatory: false },
    { id: "line_item", label: "Line Item", type: "hierarchy", mandatory: false },
    { id: "ad_group", label: "Ad Group", type: "hierarchy", mandatory: false },
    { id: "creative", label: "Creative", type: "hierarchy", mandatory: false },
    { id: "audience", label: "Audience", type: "dimension", mandatory: false },
    { id: "spend", label: "Spend", type: "metric", mandatory: true },
    { id: "impressions", label: "Impressions", type: "metric", mandatory: true },
    { id: "clicks", label: "Clicks", type: "metric", mandatory: false },
    { id: "video_views", label: "Video Views", type: "metric", mandatory: false },
  ],

  publishers: {
    dv360: {
      id: "dv360",
      name: "DV360",
      aliases: ["dv360", "display & video 360", "display video 360", "dbm"],
      hierarchy: [
        { level: 1, name: "Advertiser", mandatory: true },
        { level: 2, name: "Campaign", mandatory: true },
        { level: 3, name: "Insertion Order", mandatory: true },
        { level: 4, name: "Line Item", mandatory: true },
        { level: 5, name: "Creative", mandatory: false },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
        { name: "Brand Family", mandatory: false },
        { name: "Campaign", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: false },
      ],
    },
    cm360: {
      id: "cm360",
      name: "CM360",
      aliases: ["cm360", "campaign manager", "campaign manager 360", "dcm"],
      hierarchy: [
        { level: 1, name: "Advertiser", mandatory: true },
        { level: 2, name: "Campaign", mandatory: true },
        { level: 3, name: "Placement", mandatory: true },
        { level: 4, name: "Ad", mandatory: true },
        { level: 5, name: "Creative", mandatory: false },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: false },
      ],
    },
    google_ads: {
      id: "google_ads",
      name: "Google Ads",
      aliases: ["google ads", "googleads", "adwords", "search ads"],
      hierarchy: [
        { level: 1, name: "Account", mandatory: true },
        { level: 2, name: "Campaign", mandatory: true },
        { level: 3, name: "Ad Group", mandatory: true },
        { level: 4, name: "Keyword / Ad", mandatory: false },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: true },
      ],
    },
    facebook: {
      id: "facebook",
      name: "Facebook",
      aliases: ["facebook", "fb", "meta", "meta ads", "facebook ads"],
      hierarchy: [
        { level: 1, name: "Account", mandatory: true },
        { level: 2, name: "Campaign", mandatory: true },
        { level: 3, name: "Ad Set", mandatory: true },
        { level: 4, name: "Ad", mandatory: true },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
        { name: "Audience", mandatory: false },
        { name: "Campaign Objective", mandatory: false },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: false },
        { name: "Video Views", type: "Numeric", mandatory: false },
      ],
    },
    amazon_dsp: {
      id: "amazon_dsp",
      name: "Amazon DSP",
      aliases: ["amazon dsp", "amazon_dsp", "a9", "amazon advertising dsp"],
      hierarchy: [
        { level: 1, name: "Advertiser", mandatory: true },
        { level: 2, name: "Order", mandatory: true },
        { level: 3, name: "Line Item", mandatory: true },
        { level: 4, name: "Creative", mandatory: false },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: false },
      ],
    },
    tiktok: {
      id: "tiktok",
      name: "TikTok",
      aliases: ["tiktok", "tik tok", "tiktok ads"],
      hierarchy: [
        { level: 1, name: "Advertiser", mandatory: true },
        { level: 2, name: "Campaign", mandatory: true },
        { level: 3, name: "Ad Group", mandatory: true },
        { level: 4, name: "Ad", mandatory: true },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Video Views", type: "Numeric", mandatory: false },
      ],
    },
    linkedin: {
      id: "linkedin",
      name: "LinkedIn",
      aliases: ["linkedin", "linkedin ads"],
      hierarchy: [
        { level: 1, name: "Account", mandatory: true },
        { level: 2, name: "Campaign Group", mandatory: true },
        { level: 3, name: "Campaign", mandatory: true },
        { level: 4, name: "Creative", mandatory: false },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: false },
      ],
    },
    retail_media: {
      id: "retail_media",
      name: "Retail Media",
      aliases: ["retail media", "amazon retail", "walmart connect", "instacart ads"],
      hierarchy: [
        { level: 1, name: "Advertiser", mandatory: true },
        { level: 2, name: "Campaign", mandatory: true },
        { level: 3, name: "Ad Group", mandatory: true },
        { level: 4, name: "Product / ASIN", mandatory: false },
      ],
      dimensions: [
        { name: "Country", mandatory: true },
        { name: "Category", mandatory: true },
        { name: "Brand", mandatory: true },
      ],
      metrics: [
        { name: "Impressions", type: "Numeric", mandatory: true },
        { name: "Spend", type: "Numeric", mandatory: true },
        { name: "Clicks", type: "Numeric", mandatory: false },
      ],
    },
  },

  mappingDictionary: [
    { source: "cost", target: "spend" },
    { source: "amount spent", target: "spend" },
    { source: "amount_spent", target: "spend" },
    { source: "media cost", target: "spend" },
    { source: "media_cost", target: "spend" },
    { source: "total_cost", target: "spend" },
    { source: "total cost", target: "spend" },
    { source: "ad spend", target: "spend" },
    { source: "net cost", target: "spend" },
    { source: "imps", target: "impressions" },
    { source: "impression", target: "impressions" },
    { source: "total impressions", target: "impressions" },
    { source: "ad views", target: "impressions" },
    { source: "views", target: "video_views" },
    { source: "video views", target: "video_views" },
    { source: "3s views", target: "video_views" },
    { source: "campaign name", target: "campaign" },
    { source: "campaign_name", target: "campaign" },
    { source: "campaign type", target: "campaign_type" },
    { source: "objective", target: "campaign_objective" },
    { source: "country", target: "country" },
    { source: "market", target: "country" },
    { source: "geo", target: "country" },
    { source: "brand name", target: "brand" },
    { source: "advertiser name", target: "advertiser" },
    { source: "insertion order", target: "insertion_order" },
    { source: "io name", target: "insertion_order" },
    { source: "line item", target: "line_item" },
    { source: "line_item_name", target: "line_item" },
    { source: "ad set", target: "ad_group" },
    { source: "adset name", target: "ad_group" },
    { source: "ad group", target: "ad_group" },
    { source: "creative name", target: "creative" },
    { source: "date", target: "date" },
    { source: "day", target: "date" },
    { source: "report date", target: "date" },
    { source: "week start date", target: "date" },
    { source: "clicks", target: "clicks" },
    { source: "link clicks", target: "clicks" },
    { source: "publisher", target: "publisher" },
    { source: "platform", target: "channel" },
    { source: "media type", target: "channel" },
    { source: "category", target: "category" },
    { source: "product category", target: "category" },
  ],

  synonymLibraries: {
    Country: {
      USA: ["US", "U.S.", "United States", "United States of America"],
      "United Kingdom": ["UK", "U.K.", "Great Britain", "GB", "Britain"],
      Germany: ["DE", "Deutschland", "GER"],
      France: ["FR", "FRA"],
      Japan: ["JP", "JPN"],
    },
    Brand: {
      Alpro: ["Alpro Plant", "Alpro Dairy Free"],
      "Activia": ["Activia Yogurt", "Activia Yoghurt"],
      "Evian": ["Evian Water"],
    },
    Publisher: {
      Facebook: ["FB", "Meta", "Meta Ads", "Facebook Ads"],
      "Google Ads": ["Google", "Adwords", "Google Search"],
      DV360: ["Display & Video 360", "DBM", "DV 360"],
      "Amazon DSP": ["Amazon", "A9", "Amazon Advertising"],
      TikTok: ["Tik Tok", "TikTok Ads"],
      LinkedIn: ["LinkedIn Ads"],
    },
    Channel: {
      digital: ["display", "programmatic", "online", "digital_display", "banner", "social", "search", "video"],
      TV: ["television", "linear_tv", "broadcast_tv"],
      "out of home": ["ooh", "outdoor", "billboard", "dooh"],
    },
    Category: {
      Dairy: ["Yogurt", "Yoghurt", "Plant Dairy"],
      Water: ["Bottled Water", "Mineral Water"],
    },
    Audience: {
      "Prospecting": ["Prospect", "Cold", "Acquisition"],
      "Retargeting": ["Retarget", "Remarketing", "Warm"],
    },
    "Campaign Objective": {
      Awareness: ["Reach", "Brand Awareness", "Video Views"],
      Consideration: ["Traffic", "Engagement"],
      Conversion: ["Purchases", "Sales", "Conversions"],
    },
  },

  validationRules: [
    { id: "v1", group: "Structure", name: "Mandatory fields exist", detail: "Date, Publisher, Country, Brand, Campaign, Spend, Impressions" },
    { id: "v2", group: "Structure", name: "No duplicate standard columns", detail: "Each standardized field mapped at most once per file" },
    { id: "v3", group: "Structure", name: "Hierarchy present", detail: "Publisher business hierarchy levels mapped or defaulted" },
    { id: "v4", group: "Data Quality", name: "Spend ≥ 0", detail: "Numeric spend cannot be negative" },
    { id: "v5", group: "Data Quality", name: "Impressions ≥ 0", detail: "Impression counts cannot be negative" },
    { id: "v6", group: "Data Quality", name: "Date valid", detail: "Parseable date in the modeling period" },
    { id: "v7", group: "Data Quality", name: "CTR ≤ 100%", detail: "Clicks / impressions cannot exceed 1" },
    { id: "v8", group: "Business Rules", name: "Country standardized", detail: "Every country value resolves via the synonym library" },
    { id: "v9", group: "Business Rules", name: "Brand standardized", detail: "Every brand value resolves via the synonym library" },
    { id: "v10", group: "Business Rules", name: "Publisher standardized", detail: "No unmapped publisher names" },
  ],

  demoFiles: [
    {
      id: "f1",
      name: "Amazon_DSP_Aug.xlsx",
      publisherId: "amazon_dsp",
      rows: 842110,
      columns: ["Date", "Advertiser", "Order", "Line Item", "Country", "Brand Name", "Media Cost", "Impressions", "Clicks"],
    },
    {
      id: "f2",
      name: "GoogleAds_US.csv",
      publisherId: "google_ads",
      rows: 1204450,
      columns: ["Day", "Account", "Campaign Name", "Campaign Type", "Ad group", "Market", "Cost", "Imps", "Clicks"],
    },
    {
      id: "f3",
      name: "DV360_UK.xlsx",
      publisherId: "dv360",
      rows: 1458320,
      columns: ["Date", "Advertiser Name", "Campaign", "IO Name", "Line Item", "Creative Name", "Geo", "Brand", "Total Cost", "Impressions", "Clicks"],
    },
    {
      id: "f4",
      name: "Facebook_Ads_Q3.csv",
      publisherId: "facebook",
      rows: 510220,
      columns: ["Reporting starts", "Account name", "Campaign name", "Ad set name", "Ad name", "Country", "Amount spent", "Impressions", "Link clicks", "3s views"],
    },
  ],

  demoHarmonization: {
    Country: [
      { raw: "US", suggested: "USA", auto: true },
      { raw: "United States", suggested: "USA", auto: true },
      { raw: "United States of America", suggested: "USA", auto: true },
      { raw: "UK", suggested: "United Kingdom", auto: true },
      { raw: "Great Britain", suggested: "United Kingdom", auto: true },
      { raw: "Utd Kingdom", suggested: "United Kingdom", auto: false },
      { raw: "Deutschland", suggested: "Germany", auto: true },
      { raw: "GER-North", suggested: null, auto: false },
    ],
    Brand: [
      { raw: "Alpro Plant", suggested: "Alpro", auto: true },
      { raw: "Alpro Dairy Free", suggested: "Alpro", auto: true },
      { raw: "Activia Yoghurt", suggested: "Activia", auto: true },
      { raw: "Alpro+", suggested: null, auto: false },
      { raw: "Activia Kids", suggested: null, auto: false },
    ],
    Publisher: [
      { raw: "FB", suggested: "Facebook", auto: true },
      { raw: "Meta", suggested: "Facebook", auto: true },
      { raw: "Meta Ads", suggested: "Facebook", auto: true },
      { raw: "Adwords", suggested: "Google Ads", auto: true },
      { raw: "DBM", suggested: "DV360", auto: true },
      { raw: "Amazon Advertising", suggested: "Amazon DSP", auto: true },
    ],
  },

  demoIssues: [
    { id: "e1", kind: "unmapped_column", file: "Facebook_Ads_Q3.csv", label: "Quality ranking", detail: "No dictionary match — decide Exclude or add a mapping." },
    { id: "e2", kind: "unmapped_column", file: "DV360_UK.xlsx", label: "Floodlight activity", detail: "Publisher-specific metric, not in the standard template." },
    { id: "e3", kind: "unknown_country", file: "DV360_UK.xlsx", label: "GER-North", detail: "Not in Country synonym library." },
    { id: "e4", kind: "unknown_country", file: "GoogleAds_US.csv", label: "Utd Kingdom", detail: "Near-match to United Kingdom — confirm." },
    { id: "e5", kind: "unknown_brand", file: "Amazon_DSP_Aug.xlsx", label: "Alpro+", detail: "Not in Brand synonym library." },
    { id: "e6", kind: "unknown_brand", file: "Facebook_Ads_Q3.csv", label: "Activia Kids", detail: "Possible new brand line — confirm or add synonym." },
    { id: "e7", kind: "validation", file: "GoogleAds_US.csv", rule: "CTR ≤ 100%", detail: "3 rows with clicks > impressions." },
    { id: "e8", kind: "validation", file: "Amazon_DSP_Aug.xlsx", rule: "Date valid", detail: "2 rows with Excel serial 0 (1899-12-30)." },
    { id: "e9", kind: "validation", file: "DV360_UK.xlsx", rule: "Spend ≥ 0", detail: "1 row with spend −12.40 (credit)." },
  ],

  profiles: [
    { id: "kirin", name: "Kirin APAC Digital", publishers: ["google_ads", "facebook", "tiktok"], note: "APAC digital onboard — reuse next month." },
    { id: "bt_uk", name: "BT UK MMM", publishers: ["dv360", "cm360", "google_ads"], note: "UK MMM weekly refresh." },
  ],
};
