"""
Tool Validator - Schema-based validation for LLM tool calls.

This module provides validation and normalization for tool calls generated by LLMs,
including:
- Tool name validation with fuzzy matching
- Parameter type checking and coercion
- Required/optional parameter enforcement
- Handling of common LLM hallucinations
"""
import json
import logging
from typing import Dict, List, Any, Set, Tuple, Optional, Union
from dataclasses import dataclass, field
import difflib

logger = logging.getLogger(__name__)


# ===== Tool Schema Registry =====

@dataclass
class ParamSchema:
    """Schema for a tool parameter."""
    name: str
    param_type: type  # int, float, str, list, dict, bool
    required: bool = True
    default: Any = None
    description: str = ""
    aliases: List[str] = field(default_factory=list)  # Common hallucinated names


@dataclass
class ToolSchema:
    """Schema for a transformation tool."""
    name: str
    description: str
    params: List[ParamSchema]
    aliases: List[str] = field(default_factory=list)  # Common hallucinated names
    destructive: bool = False  # If True, requires HITL confirmation
    
    def get_required_params(self) -> List[str]:
        """Get list of required parameter names."""
        return [p.name for p in self.params if p.required]
    
    def get_optional_params(self) -> List[str]:
        """Get list of optional parameter names."""
        return [p.name for p in self.params if not p.required]
    
    def get_param_schema(self, name: str) -> Optional[ParamSchema]:
        """Get schema for a parameter by name or alias."""
        for p in self.params:
            if p.name == name or name in p.aliases:
                return p
        return None


# Tool schemas registry
# Namespace scheme: discovery.*, layout.*, transform.*, verify.*
# All old names (flat + xls.*) are preserved as aliases for backward compatibility.
TOOL_SCHEMAS: Dict[str, ToolSchema] = {
    # ===== DISCOVERY =====
    "discovery.inventory": ToolSchema(
        name="discovery.inventory",
        description="List all sheets, named ranges, hidden tabs, and dimensions of an Excel workbook",
        aliases=["get_file_inventory", "file_inventory", "list_sheets", "xls.discovery.inventory"],
        destructive=False,
        params=[
            ParamSchema("file_path", str, required=True, aliases=["filepath", "path"]),
        ]
    ),

    "discovery.inspect": ToolSchema(
        name="discovery.inspect",
        description="Deterministic structural scan of an Excel sheet",
        aliases=["inspect_sheet_structure", "sheet_structure", "xray_sheet", "xls.discovery.inspect"],
        destructive=False,
        params=[
            ParamSchema("file_path", str, required=True, aliases=["filepath", "path"]),
            ParamSchema("sheet_name", str, required=False, default=None, aliases=["sheet"]),
        ]
    ),

    "discovery.propose_file_relationships": ToolSchema(
        name="discovery.propose_file_relationships",
        description=(
            "Propose how multiple uploaded sources should combine (union/join). "
            "Uses ``context_packet.available_source_summaries``; does not mutate the dataframe. "
            "May pause for FILE_RELATIONSHIP_REVIEW when proposals exist and relationships are not yet approved."
        ),
        aliases=["propose_file_relationships", "infer_file_relationships"],
        destructive=False,
        params=[],
    ),

    # ===== LAYOUT =====
    "layout.extract": ToolSchema(
        name="layout.extract",
        description="Extract a rectangular block of data from the grid",
        aliases=["extract_data_block", "extract_block", "get_data_block", "extract_table", "xls.layout.extract"],
        destructive=False,
        params=[
            ParamSchema("start_row", int, required=True, aliases=["row_start", "from_row"]),
            ParamSchema("end_row", int, required=True, aliases=["row_end", "to_row"]),
            ParamSchema("start_col", int, required=True, aliases=["col_start", "from_col"]),
            ParamSchema("end_col", int, required=True, aliases=["col_end", "to_col"]),
            ParamSchema("header_row", int, required=True, aliases=["headers_row", "header"]),
        ]
    ),

    "layout.stack": ToolSchema(
        name="layout.stack",
        description="Stack multiple data blocks (tables) into one",
        aliases=["stack_tables", "merge_blocks", "combine_blocks", "merge_tables", "concatenate_blocks", "xls.layout.stack"],
        destructive=False,
        params=[
            ParamSchema("header_row", int, required=True, aliases=["header_index", "master_header"]),
            ParamSchema("blocks", list, required=True, aliases=["block_definitions", "block_coords"]),
        ]
    ),

    "layout.unpivot_matrix": ToolSchema(
        name="layout.unpivot_matrix",
        description="Unpivot a crosstab/matrix where both row and column headers represent dimensions",
        aliases=["crosstab_unpivot", "unpivot_matrix", "matrix_to_long", "xls.reshape.unpivot_matrix"],
        destructive=True,
        params=[
            ParamSchema("row_header_col", int, required=False, default=0),
            ParamSchema("col_header_row", int, required=False, default=0),
            ParamSchema("data_start_row", int, required=False, default=1),
            ParamSchema("data_start_col", int, required=False, default=1),
            ParamSchema("row_dim_name", str, required=False, default="Row"),
            ParamSchema("col_dim_name", str, required=False, default="Column"),
            ParamSchema("value_name", str, required=False, default="Value"),
            ParamSchema("id_cols", list, required=False, default=None, aliases=["id_columns", "bypass_cols"]),
        ]
    ),

    "layout.merge_headers": ToolSchema(
        name="layout.merge_headers",
        description="Merge multiple rows into a single header row",
        aliases=["merge_header_rows", "combine_headers", "join_headers", "multi_level_headers", "xls.header.collapse"],
        destructive=True,
        params=[
            ParamSchema("header_rows", list, required=True, aliases=["rows"]),
            ParamSchema("separator", str, required=False, default=" - "),
            ParamSchema("strip_unnamed", bool, required=False, default=True),
        ]
    ),

    "layout.filter_header_repeats": ToolSchema(
        name="layout.filter_header_repeats",
        description="Remove rows where values match column names (repeated headers in data)",
        aliases=["filter_header_rows", "remove_header_rows", "filter_repeated_headers", "xls.header.filter_repeats"],
        destructive=True,
        params=[
            ParamSchema("threshold", float, required=False, default=0.5, aliases=["similarity_threshold"]),
        ]
    ),

    # ===== TRANSFORM =====
    "transform.fill_merged": ToolSchema(
        name="transform.fill_merged",
        description=(
            "Fill merged cell values down or right to propagate parent values to child rows. "
            "Use only for **dimensions** (Ref, Name, Market, publisher, etc.). "
            "Do **not** use for block-level **budget/spend** totals. For grouped influencer layouts "
            "prefer `transform.expand_grouped_block` (dimension forward-fill + block metric split in one pass) "
            "instead of separate fill + allocate."
        ),
        aliases=["fill_merged_cells", "fill_cells_down", "fill_down", "ffill", "forward_fill", "propagate_dimensions", "fill_dims",
                 "unmerge_and_fill", "unmerge_fill", "fill_down_values",
                 "xls.header.fill_merged", "xls.data.fill_down", "xls.header.unmerge_and_fill",
                 "transform.fill_down", "transform.unmerge_and_fill"],
        destructive=False,
        params=[
            ParamSchema("direction", str, required=False, default="down", aliases=["fill_direction"]),
            ParamSchema("columns", list, required=False, default=None, aliases=["column_indices", "cols", "dimension_cols"]),
        ]
    ),

    "transform.unmerge_and_fill": ToolSchema(
        name="transform.unmerge_and_fill",
        description=(
            "Propagate Excel merged-cell parent values into blank child rows (forward-fill). "
            "Alias of `transform.fill_merged` for trace clarity. **Dimensions only**—never "
            "budget/spend. For merged metric totals use `transform.expand_grouped_block`."
        ),
        aliases=["transform.fill_merged", "unmerge_and_fill", "unmerge_fill"],
        destructive=False,
        params=[
            ParamSchema("direction", str, required=False, default="down", aliases=["fill_direction"]),
            ParamSchema("columns", list, required=False, default=None, aliases=["column_indices", "cols", "dimension_cols"]),
        ],
    ),

    "transform.allocate_block_metric": ToolSchema(
        name="transform.allocate_block_metric",
        description=(
            "Expand grouped/influencer-style rows with metric semantics: split a block-level metric across "
            "every row before SUM rollup. **Equal:** row_value = block_total / rows_in_block. "
            "**Weighted:** row_value = block_total × (row_weight / sum_weights_in_block). "
            "`weight_col` required when `method=by_weight` (e.g. impressions). "
            "Allocation method must come from planner review — do not default to weighted. "
            "Place after rename/type_cast, before aggregate_weekly. Not a substitute for fill_merged "
            "(dimensions vs budget duplication)."
        ),
        aliases=[
            "allocate_block_metric",
            "split_block_metric",
            "prorate_block_total",
            "distribute_parent_metric",
            "xls.data.allocate_block_metric",
            "expand_grouped_rows_with_metric_semantics",
            "Expand_Grouped_Rows_With_Metric_Semantics",
            "expand_grouped_rows_to_flat_table",
            "Expand_Grouped_Rows_To_Flat_Table",
        ],
        destructive=False,
        params=[
            ParamSchema("metric_col", Any, required=True, aliases=["metric", "value_col", "budget_col"]),
            ParamSchema(
                "block_start_columns",
                list,
                required=True,
                aliases=["boundary_columns", "block_keys", "parent_row_columns", "section_start_columns"],
            ),
            ParamSchema("method", str, required=False, default="equal", aliases=["mode", "allocation"]),
            ParamSchema(
                "weight_col",
                Any,
                required=False,
                default=None,
                aliases=["weights", "basis_col", "proportion_col", "impressions_col"],
            ),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
            ParamSchema(
                "merged_metric_ranges",
                list,
                required=False,
                default=None,
                aliases=["merged_ranges", "excel_merged_metric_ranges"],
            ),
        ]
    ),

    "transform.expand_grouped_block": ToolSchema(
        name="transform.expand_grouped_block",
        description=(
            "Grouped-row expand: segment on sparse block-start columns, forward-fill **dimension** columns "
            "within each block only, then split **block-level** metrics (equal or by_weight) such as spends. "
            "Row-level metrics (e.g. impressions on every child row) are never overwritten. Use instead of "
            "`fill_merged` + `allocate_block_metric` on the same sheet. Never forward-fills metric columns."
        ),
        aliases=[
            "expand_grouped_block",
            "expand_grouped_rows",
            "fill_dimensions_and_allocate_metrics",
            "grouped_block_expand",
        ],
        destructive=False,
        params=[
            ParamSchema(
                "dimension_columns",
                list,
                required=True,
                aliases=["dimension_cols", "columns", "fill_columns", "propagate_columns"],
            ),
            ParamSchema(
                "block_start_columns",
                list,
                required=False,
                default=None,
                aliases=["boundary_columns", "block_keys", "parent_row_columns", "section_start_columns"],
            ),
            ParamSchema(
                "allocations",
                list,
                required=False,
                default=None,
                aliases=["block_level_metrics", "metric_allocations"],
            ),
            ParamSchema("auto_detect_block_metrics", bool, required=False, default=True),
            ParamSchema("child_numeric_sparse_threshold", float, required=False, default=0.25),
            ParamSchema("parent_numeric_rate_threshold", float, required=False, default=0.55),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
            ParamSchema(
                "merged_metric_ranges",
                list,
                required=False,
                default=None,
                aliases=["merged_ranges", "excel_merged_metric_ranges"],
            ),
        ],
    ),

    "transform.classify_metric_level": ToolSchema(
        name="transform.classify_metric_level",
        description=(
            "Deterministic heuristic: classify numeric columns into **block header total vs post-row metric** grain "
            "using the same ``block_start_columns`` segmentation as allocate_block_metric. "
            "Read `changes_made.metric_level_report` + message JSON for **`suggested_allocate_block_metric`** "
            "(equal vs by_weight when a post-row weight column exists). Leaves the dataframe unchanged."
        ),
        aliases=[
            "classify_metric_level",
            "Classify_Metric_Level",
            "infer_metric_grain",
            "metric_grain_classifier",
            "xls.data.classify_metric_level",
        ],
        destructive=False,
        params=[
            ParamSchema(
                "block_start_columns",
                list,
                required=False,
                default=None,
                aliases=["boundary_columns", "block_keys", "parent_row_columns", "section_start_columns"],
            ),
            ParamSchema(
                "metric_columns",
                list,
                required=False,
                default=None,
                aliases=["columns", "metric_cols", "value_columns"],
            ),
            ParamSchema(
                "child_numeric_sparse_threshold",
                float,
                required=False,
                default=0.25,
                aliases=["child_sparse_threshold"],
            ),
            ParamSchema(
                "parent_numeric_rate_threshold",
                float,
                required=False,
                default=0.55,
                aliases=["parent_rate_threshold"],
            ),
            ParamSchema(
                "row_numeric_dense_threshold",
                float,
                required=False,
                default=0.42,
                aliases=["child_dense_threshold"],
            ),
            ParamSchema(
                "min_numeric_global_rate",
                float,
                required=False,
                default=0.04,
                aliases=["min_numeric_rate"],
            ),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.infer_block_boundary_columns": ToolSchema(
        name="transform.infer_block_boundary_columns",
        description=(
            "Non-destructive heuristic on the **current** dataframe that ranks candidate "
            "**block_start_columns** (same segmentation rule as allocate_block_metric/classify_metric_level). "
            "Use when raw ids such as Ref were dropped or unreliable; outputs land in "
            "`changes_made.block_boundary_inference` and the JSON `message`. "
            "Prefer running **before** dropping sparse delimiter columns."
        ),
        aliases=[
            "infer_block_boundary_columns",
            "suggest_block_start_columns",
            "infer_block_delimiters",
            "xls.data.infer_block_boundary_columns",
        ],
        destructive=False,
        params=[
            ParamSchema(
                "exclude_columns",
                list,
                required=False,
                default=None,
                aliases=["omit_columns", "skip_columns"],
            ),
            ParamSchema(
                "metric_columns_hint",
                list,
                required=False,
                default=None,
                aliases=["metrics", "metric_cols", "value_columns_hint"],
            ),
            ParamSchema("min_multi_row_blocks", int, required=False, default=2),
            ParamSchema(
                "min_nonempty_row_rate",
                float,
                required=False,
                default=0.01,
                aliases=["min_boundary_fill_rate"],
            ),
            ParamSchema(
                "max_nonempty_row_rate",
                float,
                required=False,
                default=0.92,
                aliases=["max_boundary_fill_rate"],
            ),
            ParamSchema("min_mean_segment_len", float, required=False, default=1.25),
            ParamSchema("max_pair_search", int, required=False, default=6),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.densify": ToolSchema(
        name="transform.densify",
        description="Forward-fill dimension columns and optionally remove rows with empty value columns",
        aliases=["densify_dataframe", "densify", "fill_sparse_dimensions", "xls.data.densify"],
        destructive=True,
        params=[
            ParamSchema("dimension_cols", list, required=False, default=None, aliases=["columns", "dim_cols"]),
            ParamSchema("drop_empty_value_rows", bool, required=False, default=True),
        ]
    ),


    "transform.unpivot": ToolSchema(
        name="transform.unpivot",
        description="Unpivot wide format to long format (melt). Use for both simple and hierarchical data.",
        aliases=["unpivot_columns", "melt", "unpivot", "wide_to_long", "hierarchical_unpivot", "xls.reshape.melt"],
        destructive=True,
        params=[
            ParamSchema("id_cols", list, required=True, aliases=["id_columns", "index_columns", "identifier_columns", "parent_columns"]),
            ParamSchema("value_cols", list, required=False, default=None, aliases=["value_columns", "metric_columns"]),
            ParamSchema("var_name", str, required=False, default="Variable", aliases=["variable_name", "column_name"]),
            ParamSchema("value_name", str, required=False, default="Value", aliases=["values_name"]),
        ]
    ),

    "transform.filter_empty": ToolSchema(
        name="transform.filter_empty",
        description="Remove rows where specified columns are empty",
        aliases=["filter_empty_rows", "remove_empty_rows", "drop_empty", "dropna_rows", "filter_incomplete_rows", "drop_incomplete", "xls.data.filter_empty"],
        destructive=True,
        params=[
            ParamSchema("check_columns", list, required=False, default=None, aliases=["columns", "value_cols", "values", "subset"]),
            ParamSchema("metric_columns", list, required=False, default=None, aliases=["metrics", "metric_cols"]),
            ParamSchema("all_must_be_empty", bool, required=False, default=True),
            ParamSchema("require_metrics", bool, required=False, default=False),
            ParamSchema("min_populated_columns", int, required=False, default=2),
        ]
    ),

    "transform.filter_summaries": ToolSchema(
        name="transform.filter_summaries",
        description=(
            "Remove Total/Subtotal/Grand Total rows after layout.extract — initial flat-table "
            "cleanup before rename, fill_merged, expand_grouped_block, or aggregate_weekly."
        ),
        aliases=["filter_summary_rows", "remove_totals", "filter_totals", "remove_summary", "xls.data.filter_summaries"],
        destructive=True,
        params=[
            ParamSchema("keywords", list, required=False, default=None, aliases=["summary_keywords"]),
            ParamSchema("check_columns", list, required=False, default=None, aliases=["columns"]),
            ParamSchema("use_structural_detection", bool, required=False, default=True),
            ParamSchema("numeric_threshold", float, required=False, default=0.7),
        ]
    ),

    "transform.skip_rows": ToolSchema(
        name="transform.skip_rows",
        description="Remove specified rows by index",
        aliases=["skip_rows", "remove_rows", "delete_rows", "drop_rows", "xls.data.skip_rows"],
        destructive=True,
        params=[
            ParamSchema("rows_to_skip", list, required=True, aliases=["row_indices", "rows"]),
        ]
    ),

    "transform.drop_columns": ToolSchema(
        name="transform.drop_columns",
        description="Drop specified columns",
        aliases=["drop_columns", "remove_columns", "delete_columns", "filter_summary_columns", "filter_total_cols", "select_columns", "xls.schema.drop"],
        destructive=True,
        params=[
            ParamSchema("columns", list, required=True, aliases=["cols", "names"]),
        ]
    ),

    "transform.drop_blank_columns": ToolSchema(
        name="transform.drop_blank_columns",
        description="Automatically remove columns that are entirely or mostly blank",
        aliases=["drop_blank_columns", "remove_blank_columns", "drop_empty_columns", "xls.data.drop_blank_columns"],
        destructive=True,
        params=[
            ParamSchema("threshold", float, required=False, default=1.0, aliases=["blank_threshold"]),
        ]
    ),

    "transform.rename": ToolSchema(
        name="transform.rename",
        description="Rename columns using a mapping dictionary",
        aliases=["rename_columns", "rename_cols", "set_column_names", "xls.schema.rename"],
        destructive=False,
        params=[
            ParamSchema("mapping", dict, required=True, aliases=["column_mapping", "name_mapping", "column_map", "rename_map"]),
        ]
    ),

    "transform.align_schema": ToolSchema(
        name="transform.align_schema",
        description=(
            "Deterministic union prep: reorder/rename columns to a fixed target list, "
            "optional per-target source aliases, fill missing targets"
        ),
        aliases=["align_schema", "schema_align", "union_align_columns"],
        destructive=False,
        params=[
            ParamSchema("target_columns", list, required=True, aliases=["columns", "target_cols", "column_order"]),
            ParamSchema("aliases", dict, required=False, default=None, aliases=["column_aliases", "rename_map_by_target"]),
            ParamSchema("fill_value", Any, required=False, default=None, aliases=["default_value", "na_fill"]),
        ]
    ),

    "transform.union_resolve": ToolSchema(
        name="transform.union_resolve",
        description=(
            "After concatenating sources: dedupe on key columns with conflict policy "
            "(first, sum, max, min, prefer_source)"
        ),
        aliases=["union_resolve", "keyed_dedupe", "post_union_resolve"],
        destructive=False,
        params=[
            ParamSchema("key_columns", list, required=True, aliases=["keys", "subset", "key_cols"]),
            ParamSchema("policy", str, required=False, default="first", aliases=["conflict_policy", "mode"]),
            ParamSchema("metric_columns", list, required=False, default=None, aliases=["metrics", "measure_cols"]),
            ParamSchema("source_tag_column", str, required=False, default=None, aliases=["source_column", "_source"]),
            ParamSchema("prefer_source_id", str, required=False, default=None, aliases=["prefer_source", "source_id"]),
        ]
    ),

    "transform.deduplicate": ToolSchema(
        name="transform.deduplicate",
        description="Remove duplicate rows",
        aliases=["deduplicate_rows", "unique_rows", "remove_duplicates", "xls.data.deduplicate"],
        destructive=True,
        params=[
            ParamSchema("subset", list, required=False, default=None, aliases=["columns"]),
            ParamSchema("keep", str, required=False, default="first"),
        ]
    ),

    "transform.type_cast": ToolSchema(
        name="transform.type_cast",
        description="Cast columns to appropriate data types",
        aliases=["type_cast_columns", "cast_columns", "convert_types", "xls.data.fix_types"],
        destructive=False,
        params=[
            ParamSchema("type_map", dict, required=True, aliases=["column_types", "types"]),
        ]
    ),

    "transform.transpose": ToolSchema(
        name="transform.transpose",
        description="Transpose the DataFrame (swap rows and columns)",
        aliases=["transpose_data", "transpose", "swap_axes", "xls.reshape.transpose"],
        destructive=True,
        params=[
            ParamSchema("header_col", int, required=False, default=None),
            ParamSchema("new_index_name", str, required=False, default="Column"),
        ]
    ),

    "transform.map_values": ToolSchema(
        name="transform.map_values",
        description="Map messy source values to standardized target values",
        aliases=["map_values", "remap_column", "category_map", "value_mapping", "xls.data.map_values"],
        destructive=False,
        params=[
            ParamSchema("column", str, required=True, aliases=["col", "target_column"]),
            ParamSchema("mapping", dict, required=True, aliases=["value_map", "category_mapping"]),
            ParamSchema("case_insensitive", bool, required=False, default=True),
            ParamSchema("default", str, required=False, default=None, aliases=["fallback"]),
        ]
    ),

    "transform.add_column": ToolSchema(
        name="transform.add_column",
        description=(
            "Create a missing UID/supporting column or fill with a literal default "
            "(not rename, map_values, or arithmetic calculate)"
        ),
        aliases=[
            "add_column",
            "assign_column",
            "set_column",
            "create_column",
            "literal_column",
            "xls.data.add_column",
        ],
        destructive=False,
        params=[
            ParamSchema("target_column", str, required=True, aliases=["column", "col", "new_column"]),
            ParamSchema("value", object, required=True, aliases=["literal", "default_value", "fill_value"]),
            ParamSchema(
                "when",
                str,
                required=False,
                default="missing",
                aliases=["mode", "condition"],
            ),
        ],
    ),

    "transform.apply_column_rules": ToolSchema(
        name="transform.apply_column_rules",
        description="Apply target template business_logic.column_rules (set_value when missing/null)",
        aliases=[
            "apply_column_rules",
            "apply_template_column_rules",
            "template_column_rules",
            "xls.data.apply_column_rules",
        ],
        destructive=False,
        params=[
            ParamSchema(
                "column_rules",
                list,
                required=False,
                default=None,
                aliases=["rules", "business_logic_rules"],
            ),
        ],
    ),

    "transform.calculate": ToolSchema(
        name="transform.calculate",
        description=(
            "Arithmetic only (+, -, *, /) on existing numeric columns — "
            "NOT for missing UID columns or literal defaults (use transform.add_column)"
        ),
        aliases=["calculate_column", "compute_column", "derive_column", "add_formula", "xls.data.calculate"],
        destructive=False,
        params=[
            ParamSchema("target_column", str, required=True, aliases=["output_column", "new_column"]),
            ParamSchema("expression", str, required=True, aliases=["formula", "calc"]),
            ParamSchema("source_columns", list, required=False, default=None, aliases=["input_columns"]),
        ]
    ),

    "transform.scale_values": ToolSchema(
        name="transform.scale_values",
        description=(
            "Multiply numeric columns by unit factors when headers indicate denomination "
            "(e.g. Spends in '000 → scales spends by 1000). Run after rename/type_cast."
        ),
        aliases=["scale_columns", "scale_values", "apply_value_scale", "xls.data.scale_values"],
        destructive=False,
        params=[
            ParamSchema("scales", dict, required=True, aliases=["columns", "scale_map", "factors"]),
        ],
    ),

    "transform.format": ToolSchema(
        name="transform.format",
        description="Apply formatting to columns (date, numeric, integer, case)",
        aliases=["format_columns", "apply_format", "style_columns", "xls.data.format"],
        destructive=False,
        params=[
            ParamSchema("format_map", dict, required=True, aliases=["formats", "column_formats"]),
        ]
    ),

    "transform.reorder_columns": ToolSchema(
        name="transform.reorder_columns",
        description=(
            "Reorder columns to match the target template (date, uid hierarchy, supporting, metrics). "
            "Unlisted columns are kept at the end."
        ),
        aliases=["reorder_columns", "order_columns", "xls.schema.reorder"],
        destructive=False,
        params=[
            ParamSchema(
                "column_order",
                list,
                required=True,
                aliases=["columns", "order", "preferred_order", "target_order"],
            ),
        ],
    ),

    "transform.sort_rows": ToolSchema(
        name="transform.sort_rows",
        description=(
            "Sort rows by uid hierarchy columns (date dimensions first, then remaining uid fields). "
            "Use after transforms and before verify.schema."
        ),
        aliases=["sort_rows", "sort_dataframe", "order_rows", "xls.data.sort"],
        destructive=False,
        params=[
            ParamSchema(
                "sort_columns",
                list,
                required=True,
                aliases=["columns", "by", "sort_by", "order_by"],
            ),
            ParamSchema("ascending", bool, required=False, default=True),
        ],
    ),

    "transform.date_range_to_weekly": ToolSchema(
        name="transform.date_range_to_weekly",
        description=(
            "Prorate metrics across calendar days between start/end dates, then bucket to Monday–Sunday weeks "
            "or emit daily rows"
        ),
        aliases=["date_range_to_weekly", "range_to_weekly", "weekly_from_ranges", "xls.data.date_range_to_weekly"],
        destructive=False,
        params=[
            ParamSchema("start_date_col", Any, required=True, aliases=["start_col", "start_date", "range_start"]),
            ParamSchema("end_date_col", Any, required=True, aliases=["end_col", "end_date", "range_end"]),
            ParamSchema("value_cols", list, required=True, aliases=["metrics", "measure_cols", "amount_cols"]),
            ParamSchema("id_cols", list, required=False, default=None, aliases=["group_cols", "dimension_cols"]),
            ParamSchema("granularity", str, required=False, default="weekly", aliases=["freq", "period"]),
            ParamSchema("week_start_col", str, required=False, default="week_start"),
            ParamSchema("week_end_col", str, required=False, default=None),
            ParamSchema("days_in_period_col", str, required=False, default="days_in_week"),
            ParamSchema("date_column", str, required=False, default="calendar_date"),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.expand_date_range_to_daily": ToolSchema(
        name="transform.expand_date_range_to_daily",
        description="Start/end date columns → daily rows (prorated metrics); alias of date_range_to_weekly(granularity=daily).",
        aliases=["expand_date_range_to_daily", "range_to_daily", "xls.data.expand_date_range_to_daily"],
        destructive=False,
        params=[
            ParamSchema("start_date_col", Any, required=True, aliases=["start_col", "start_date", "range_start"]),
            ParamSchema("end_date_col", Any, required=True, aliases=["end_col", "end_date", "range_end"]),
            ParamSchema("value_cols", list, required=True, aliases=["metrics", "measure_cols", "amount_cols"]),
            ParamSchema("id_cols", list, required=False, default=None, aliases=["group_cols", "dimension_cols"]),
            ParamSchema("week_start_col", str, required=False, default="week_start"),
            ParamSchema("week_end_col", str, required=False, default=None),
            ParamSchema("days_in_period_col", str, required=False, default="days_in_week"),
            ParamSchema("date_column", str, required=False, default="calendar_date"),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ],
    ),

    "transform.expand_date_range_to_weekly": ToolSchema(
        name="transform.expand_date_range_to_weekly",
        description="Start/end date columns → ISO weekly buckets; alias of date_range_to_weekly(granularity=weekly).",
        aliases=["expand_date_range_to_weekly", "range_expand_weekly", "xls.data.expand_date_range_to_weekly"],
        destructive=False,
        params=[
            ParamSchema("start_date_col", Any, required=True, aliases=["start_col", "start_date", "range_start"]),
            ParamSchema("end_date_col", Any, required=True, aliases=["end_col", "end_date", "range_end"]),
            ParamSchema("value_cols", list, required=True, aliases=["metrics", "measure_cols", "amount_cols"]),
            ParamSchema("id_cols", list, required=False, default=None, aliases=["group_cols", "dimension_cols"]),
            ParamSchema("week_start_col", str, required=False, default="week_start"),
            ParamSchema("week_end_col", str, required=False, default=None),
            ParamSchema("days_in_period_col", str, required=False, default="days_in_week"),
            ParamSchema("date_column", str, required=False, default="calendar_date"),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ],
    ),

    "transform.aggregate_weekly": ToolSchema(
        name="transform.aggregate_weekly",
        description=(
            "Aggregate a dataframe with an existing daily/date column into Monday–Sunday "
            "weekly buckets using per-metric aggregation rules."
        ),
        aliases=[
            "aggregate_weekly",
            "weekly_aggregate",
            "weekly_rollup",
            "rollup_weekly",
            "daily_to_weekly",
            "transform.weekly_rollup",
            "xls.data.aggregate_weekly",
        ],
        destructive=False,
        params=[
            ParamSchema("date_col", Any, required=True, aliases=["date_column", "date", "day_col"]),
            ParamSchema("group_by_cols", list, required=False, default=None, aliases=["group_by", "dimension_cols", "id_cols"]),
            ParamSchema("metric_rules", dict, required=False, default=None, aliases=["aggregations", "agg_map", "metrics_map", "metric_aggregations"]),
            ParamSchema("value_cols", list, required=False, default=None, aliases=["metrics", "measure_cols", "amount_cols"]),
            ParamSchema("week_start_col", str, required=False, default=None),
            ParamSchema("week_end_col", str, required=False, default=None),
            ParamSchema("drop_original_date", bool, required=False, default=True, aliases=["drop_date"]),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.build_date_from_parts": ToolSchema(
        name="transform.build_date_from_parts",
        description=(
            "Build a real date column from separate year/month/day columns, or from year + quarter."
        ),
        aliases=[
            "build_date_from_parts",
            "compose_date_from_parts",
            "make_date_from_parts",
            "combine_date_parts",
            "xls.data.build_date_from_parts",
        ],
        destructive=False,
        params=[
            ParamSchema("year_col", Any, required=True, aliases=["year", "year_column"]),
            ParamSchema("month_col", Any, required=False, default=None, aliases=["month", "month_column"]),
            ParamSchema("day_col", Any, required=False, default=None, aliases=["day", "day_column"]),
            ParamSchema("quarter_col", Any, required=False, default=None, aliases=["quarter", "quarter_column"]),
            ParamSchema("target_date_col", str, required=False, default="calendar_date", aliases=["output_date_col", "date_col"]),
            ParamSchema("default_day", int, required=False, default=1),
            ParamSchema("drop_source_columns", bool, required=False, default=False, aliases=["remove_source_columns", "drop_parts"]),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.expand_period_to_daily": ToolSchema(
        name="transform.expand_period_to_daily",
        description=(
            "Expand monthly or quarterly period rows into daily rows by prorating metrics equally across the period."
        ),
        aliases=[
            "expand_period_to_daily",
            "period_to_daily",
            "expand_monthly_to_daily",
            "expand_quarterly_to_daily",
            "xls.data.expand_period_to_daily",
        ],
        destructive=False,
        params=[
            ParamSchema("date_col", Any, required=True, aliases=["date_column", "period_date_col"]),
            ParamSchema("value_cols", list, required=True, aliases=["metrics", "measure_cols", "amount_cols"]),
            ParamSchema("input_granularity", str, required=True, aliases=["granularity", "period_granularity", "freq"]),
            ParamSchema("id_cols", list, required=False, default=None, aliases=["group_cols", "dimension_cols"]),
            ParamSchema("date_column", str, required=False, default="calendar_date"),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.infer_granularity_expand_to_daily": ToolSchema(
        name="transform.infer_granularity_expand_to_daily",
        description=(
            "Infer coarse date cadence from the date column (sorted-unique gap heuristics), then expand to "
            "daily rows for monthly/quarterly/weekly totals, treat irregular/sporadic as daily (no calendar expand), "
            "or no-op when already daily. Prefer before aggregate_weekly when source grain is unclear."
        ),
        aliases=[
            "infer_granularity_expand_to_daily",
            "infer_cadence_expand_daily",
            "auto_expand_to_daily",
            "xls.data.infer_granularity_expand_to_daily",
        ],
        destructive=False,
        params=[
            ParamSchema(
                "date_col",
                Any,
                required=True,
                aliases=["period_date_col", "source_date_col"],
            ),
            ParamSchema("value_cols", list, required=True, aliases=["metrics", "measure_cols", "amount_cols"]),
            ParamSchema("id_cols", list, required=False, default=None, aliases=["group_cols", "dimension_cols"]),
            ParamSchema(
                "date_column",
                str,
                required=False,
                default="calendar_date",
                aliases=["output_date_col", "daily_date_col"],
            ),
            ParamSchema("min_confidence", float, required=False, default=0.35),
            ParamSchema("row_filters", list, required=False, default=None, aliases=["filters", "where"]),
        ]
    ),

    "transform.align_columns": ToolSchema(
        name="transform.align_columns",
        description="Align column names between two schemas using fuzzy matching and synonyms",
        aliases=["fuzzy_column_align", "align_columns", "match_columns", "xls.schema.align_columns"],
        destructive=False,
        params=[
            ParamSchema("source_columns", list, required=True, aliases=["source_cols"]),
            ParamSchema("target_columns", list, required=True, aliases=["target_cols"]),
        ]
    ),

    "transform.fuzzy_standardize": ToolSchema(
        name="transform.fuzzy_standardize",
        description="Standardize inconsistent labels in a column",
        aliases=["fuzzy_standardize_column", "clean_labels", "fuzzy_normalize", "group_similar"],
        destructive=False,
        params=[
            ParamSchema("column", Any, required=True, aliases=["col_index", "target_column"]),
            ParamSchema("threshold", float, required=False, default=0.85),
            ParamSchema("case_sensitive", bool, required=False, default=False),
        ]
    ),

    "transform.split_column": ToolSchema(
        name="transform.split_column",
        description="Split a column into multiple columns",
        aliases=["split_column", "split_col", "break_column", "expand_column"],
        destructive=False,
        params=[
            ParamSchema("column", Any, required=True, aliases=["col_index", "target_column"]),
            ParamSchema("new_names", list, required=True, aliases=["column_names", "headers"]),
            ParamSchema("separator", str, required=False, default=" - "),
            ParamSchema("remove_original", bool, required=False, default=True),
        ]
    ),

    # ===== VERIFY =====
    "verify.checksum": ToolSchema(
        name="verify.checksum",
        description="Verify data integrity by comparing column sum against expected total",
        aliases=["verify_checksum", "checksum", "verify_total", "xls.validation.checksum"],
        destructive=False,
        params=[
            ParamSchema("checksum_column", str, required=True, aliases=["column", "sum_column"]),
            ParamSchema("expected_total", float, required=True, aliases=["total", "expected"]),
            ParamSchema("tolerance", float, required=False, default=0.01),
        ]
    ),

    "verify.schema": ToolSchema(
        name="verify.schema",
        description="Validate DataFrame against a JSON Schema",
        aliases=["validate_against_schema", "schema_check", "validate_output", "xls.utils.validate_schema"],
        destructive=False,
        params=[
            ParamSchema("schema", dict, required=True, aliases=["json_schema", "target_schema"]),
        ]
    ),

    "validate.cross_source_union": ToolSchema(
        name="validate.cross_source_union",
        description=(
            "Read-only union readiness: column intersection across sources, optional dtype mismatch, "
            "date grain hints (input table unchanged)"
        ),
        aliases=["cross_source_union_validate", "validate_union", "union_readiness"],
        destructive=False,
        params=[
            ParamSchema("column_sets_by_source", dict, required=True, aliases=["columns_by_source", "per_source_columns"]),
            ParamSchema("key_hints", list, required=False, default=None, aliases=["grain_hints", "join_keys"]),
            ParamSchema("dtype_map_by_source", dict, required=False, default=None, aliases=["dtypes_by_source"]),
            ParamSchema("date_granularity_by_source", dict, required=False, default=None, aliases=["date_grain_by_source"]),
        ]
    ),

    # ===== COLLATION (post-union combined frame; local execution in execute_tools / parent graph) =====
    "collation.reorder_columns": ToolSchema(
        name="collation.reorder_columns",
        description="Reorder columns on a combined dataframe to match template or canonical merge order.",
        aliases=["merge_reorder_columns", "collation_reorder"],
        destructive=False,
        params=[
            ParamSchema("column_order", list, required=True, aliases=["columns", "order", "preferred_order"]),
        ],
    ),
    "collation.drop_duplicate_rows": ToolSchema(
        name="collation.drop_duplicate_rows",
        description="Drop duplicate rows on the combined frame (subset keys optional).",
        aliases=["collation.remove_duplicates", "merge_drop_duplicate_rows"],
        destructive=True,
        params=[
            ParamSchema("subset", list, required=False, default=None, aliases=["columns", "keys"]),
            ParamSchema("keep", str, required=False, default="first", aliases=["keep_strategy"]),
        ],
    ),
    "collation.aggregate_duplicate_keys": ToolSchema(
        name="collation.aggregate_duplicate_keys",
        description="Aggregate measures within duplicate join-key groups on the combined union stack.",
        aliases=["collation.aggregate_duplicates", "merge_aggregate_duplicate_keys"],
        destructive=True,
        params=[
            ParamSchema("group_keys", list, required=True, aliases=["keys", "join_keys", "subset"]),
            ParamSchema("sum_columns", list, required=False, default=None, aliases=["metrics", "measure_cols"]),
        ],
    ),
    "collation.resolve_duplicate_key_groups": ToolSchema(
        name="collation.resolve_duplicate_key_groups",
        description="Resolve duplicate-key groups using per-group decisions (exact vs partial overlap).",
        aliases=["collation.resolve_duplicate_groups", "merge_resolve_duplicate_key_groups"],
        destructive=True,
        params=[
            ParamSchema("group_keys", list, required=True, aliases=["keys", "join_keys"]),
            ParamSchema("decisions", dict, required=True, aliases=["group_decisions", "duplicate_key_group_decisions"]),
            ParamSchema("default_exact", str, required=False, default="treat_duplicate"),
            ParamSchema("default_partial", str, required=False, default="keep_both"),
        ],
    ),
}


# ===== Validation Functions =====

@dataclass
class ValidationResult:
    """Result of tool call validation."""
    valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    normalized_tool_name: str = ""
    normalized_params: Dict[str, Any] = field(default_factory=dict)


def normalize_tool_name(tool_name: Union[str, None]) -> Tuple[str, bool]:
    """
    Normalize a potentially hallucinated tool name to the correct name.
    
    Args:
        tool_name: The tool name from LLM (may be hallucinated)
        
    Returns:
        Tuple of (normalized_name, was_corrected)
    """
    if tool_name is None:
        return "", False
        
    # Exact match (including compatibility keys) - always return canonical schema.name
    if tool_name in TOOL_SCHEMAS:
        canonical_name = TOOL_SCHEMAS[tool_name].name
        return canonical_name, canonical_name != tool_name
    
    # Check aliases and case-insensitive canonical names
    tool_name_lower = tool_name.lower().strip()
    
    for canonical_name, schema in TOOL_SCHEMAS.items():
        # Case-insensitive canonical match
        if tool_name_lower == canonical_name.lower():
            return canonical_name, True
            
        # Alias match
        if tool_name_lower in [a.lower() for a in schema.aliases] or tool_name in schema.aliases:
            logger.info(f"Tool name '{tool_name}' normalized to '{canonical_name}' via alias")
            return canonical_name, True
    
    return tool_name, False


def normalize_param_name(tool_schema: ToolSchema, param_name: str) -> Tuple[str, bool]:
    """
    Normalize a potentially hallucinated parameter name.
    
    Args:
        tool_schema: The tool's schema
        param_name: The parameter name from LLM
        
    Returns:
        Tuple of (normalized_name, was_corrected)
    """
    # Check direct match
    for ps in tool_schema.params:
        if ps.name == param_name:
            return param_name, False
    
    # Check aliases
    for ps in tool_schema.params:
        if param_name in ps.aliases:
            logger.debug(f"Param '{param_name}' normalized to '{ps.name}'")
            return ps.name, True
    
    return param_name, False


def coerce_param_type(value: Any, expected_type: type) -> Tuple[Any, bool, str]:
    """
    Attempt to coerce a value to the expected type.
    
    Args:
        value: The value to coerce
        expected_type: The target type
        
    Returns:
        Tuple of (coerced_value, success, error_message)
    """
    if value is None:
        return None, True, ""

    if expected_type is Any:
        return value, True, ""

    if isinstance(value, expected_type):
        return value, True, ""
    
    try:
        if expected_type == int:
            return int(float(value)), True, ""
        elif expected_type == float:
            return float(value), True, ""
        elif expected_type == str:
            return str(value), True, ""
        elif expected_type == bool:
            if isinstance(value, str):
                return value.lower() in ('true', '1', 'yes'), True, ""
            return bool(value), True, ""
        elif expected_type == list:
            if isinstance(value, str):
                # Try to parse as JSON array
                import json
                return json.loads(value), True, ""
            return list(value), True, ""
        elif expected_type == dict:
            if isinstance(value, str):
                import json
                return json.loads(value), True, ""
            return dict(value), True, ""
    except (ValueError, TypeError) as e:
        return value, False, f"Cannot convert {type(value).__name__} to {expected_type.__name__}: {e}"
    
    return value, False, f"Unknown type coercion: {type(value).__name__} to {expected_type.__name__}"


def _normalize_expand_grouped_block_params(params: Dict[str, Any]) -> Dict[str, Any]:
    """Map legacy ``allocate_block_metric`` flat params onto ``allocations`` list."""
    out = dict(params or {})
    if out.get("allocations"):
        for legacy in ("metric_columns", "metric_col", "method", "weight_col"):
            out.pop(legacy, None)
        return out

    metrics = out.pop("metric_columns", None)
    if metrics is None:
        metrics = out.pop("metric_col", None)
    method = str(out.pop("method", "equal") or "equal").strip().lower()
    weight = out.pop("weight_col", None)
    if metrics is None and weight is None and method == "equal":
        return out

    if isinstance(metrics, str):
        metric_list = [metrics]
    elif isinstance(metrics, list):
        metric_list = [str(m) for m in metrics if m is not None and str(m).strip()]
    else:
        metric_list = [str(metrics)] if metrics is not None else []

    if not metric_list:
        return out

    if method not in ("equal", "by_weight"):
        method = "equal"
    out["allocations"] = [
        {"metric_col": m, "method": method, "weight_col": weight} for m in metric_list
    ]
    return out


def normalize_planner_tool_params(tool_name: str, params: Dict[str, Any]) -> Dict[str, Any]:
    """Coerce common LLM parameter mistakes before schema validation."""
    normalized, _ = normalize_tool_name(str(tool_name or "").strip())
    if normalized == "transform.expand_grouped_block":
        return _normalize_expand_grouped_block_params(params)
    return dict(params or {})


def validate_tool_call(tool_call: Dict[str, Any]) -> ValidationResult:
    """
    Validate and normalize a tool call from LLM.
    
    Args:
        tool_call: Dict with 'tool' and 'params' keys
        
    Returns:
        ValidationResult with validation status and normalized values
    """
    result = ValidationResult(valid=True)
    
    if not isinstance(tool_call, dict):
        result.valid = False
        result.errors.append(f"Tool call must be a dictionary, got {type(tool_call).__name__}")
        return result

    tool_name = tool_call.get("tool", "")
    params = normalize_planner_tool_params(tool_name, tool_call.get("params", {}))
    
    # Normalize tool name
    normalized_name, was_corrected = normalize_tool_name(tool_name)
    result.normalized_tool_name = normalized_name
    
    if was_corrected:
        result.warnings.append(f"Tool name '{tool_name}' corrected to '{normalized_name}'")
    
    # Check if tool exists
    if normalized_name not in TOOL_SCHEMAS:
        result.valid = False
        result.errors.append(f"Unknown tool: '{tool_name}'")
        
        # Suggest alternatives
        all_tools = list(TOOL_SCHEMAS.keys())
        suggestions = difflib.get_close_matches(tool_name, all_tools, n=3, cutoff=0.4)
        if suggestions:
            result.errors.append(f"Did you mean: {suggestions}?")
        
        return result
    
    tool_schema = TOOL_SCHEMAS[normalized_name]
    normalized_params = {}
    
    # Normalize and validate parameters
    for param_name, param_value in params.items():
        norm_name, was_param_corrected = normalize_param_name(tool_schema, param_name)
        
        if was_param_corrected:
            result.warnings.append(f"Param '{param_name}' corrected to '{norm_name}'")
        
        param_schema = tool_schema.get_param_schema(norm_name)
        
        if param_schema is None:
            # Unknown parameter - warn but don't fail
            result.warnings.append(f"Unknown parameter '{param_name}' for tool '{normalized_name}'")
            normalized_params[param_name] = param_value
            continue
        
        # Type coercion
        coerced_value, success, error_msg = coerce_param_type(param_value, param_schema.param_type)
        
        if not success:
            result.valid = False
            result.errors.append(f"Parameter '{norm_name}': {error_msg}")
        else:
            if coerced_value != param_value:
                result.warnings.append(f"Parameter '{norm_name}' coerced from {type(param_value).__name__} to {param_schema.param_type.__name__}")
            normalized_params[norm_name] = coerced_value
    
    # Check required parameters
    for required_param in tool_schema.get_required_params():
        if required_param not in normalized_params:
            # Check if there's a default
            param_schema = tool_schema.get_param_schema(required_param)
            if param_schema and param_schema.default is not None:
                normalized_params[required_param] = param_schema.default
                result.warnings.append(f"Using default for '{required_param}': {param_schema.default}")
            else:
                result.valid = False
                result.errors.append(f"Missing required parameter: '{required_param}'")
    
    # Add defaults for optional parameters if not provided
    for ps in tool_schema.params:
        if not ps.required and ps.name not in normalized_params and ps.default is not None:
            normalized_params[ps.name] = ps.default
    
    result.normalized_params = normalized_params
    
    return result


def validate_tool_sequence(tool_calls: List[Dict]) -> Tuple[List[Dict], List[str]]:
    """
    Validate and normalize a sequence of tool calls.
    
    Args:
        tool_calls: List of tool call dicts
        
    Returns:
        Tuple of (normalized_tool_calls, all_errors)
    """
    normalized_calls = []
    all_errors = []
    
    for i, tool_call in enumerate(tool_calls):
        result = validate_tool_call(tool_call)
        
        if result.valid:
            normalized_calls.append({
                "step": tool_call.get("step", i + 1),
                "tool": result.normalized_tool_name,
                "params": result.normalized_params,
                "description": tool_call.get("description", ""),
                "_validation_warnings": result.warnings
            })
        else:
            all_errors.extend([f"Step {i+1}: {e}" for e in result.errors])
            # Include the original call but mark it as invalid
            # Safe unpack: if not a dict, wrap it
            source_info = tool_call if isinstance(tool_call, dict) else {"raw_input": tool_call}
            normalized_calls.append({
                **source_info,
                "_validation_errors": result.errors,
                "_valid": False
            })
        
        if result.warnings:
            logger.info(f"Tool call {i+1} warnings: {result.warnings}")
    
    # ===== Inter-Tool Dependency Validation =====
    dep_warnings = _validate_tool_dependencies(normalized_calls)
    if dep_warnings:
        all_errors.extend(dep_warnings)
        logger.warning(f"Tool sequence dependency issues: {dep_warnings}")

    stage_warnings = _validate_stage_monotonicity(normalized_calls)
    if stage_warnings:
        all_errors.extend(stage_warnings)
        logger.warning(f"Tool sequence stage order issues: {stage_warnings}")

    return normalized_calls, all_errors


# After reshape (80); before validation (90). Unknown / unmapped tools run late but before verify.* .
_TOOL_SORT_UNKNOWN_FALLBACK = 88

# Immediately after layout.extract / layout.stack (23), before fill/expand cleanup.
_TOOL_SORT_FILTER_SUMMARIES_AFTER_EXTRACT = 24

# After column_typing (40), before date_normalisation (50) — template metric names exist.
_TOOL_SORT_EXPAND_GROUPED_BLOCK = 45

# After value_standardisation (70) when block metric tools need delimiter columns intact.
_TOOL_SORT_DROP_AFTER_BLOCK_METRICS = 72

_BLOCK_METRIC_TOOLS = frozenset(
    {
        "transform.classify_metric_level",
        "transform.allocate_block_metric",
        "transform.expand_grouped_block",
        "transform.infer_block_boundary_columns",
    }
)


def _plan_uses_block_metric_tools(tool_calls: List[Dict[str, Any]]) -> bool:
    for tc in tool_calls or []:
        if not isinstance(tc, dict):
            continue
        normalized, _ = normalize_tool_name(str(tc.get("tool") or "").strip())
        if normalized in _BLOCK_METRIC_TOOLS:
            return True
    return False


# Re-running these with identical params is a no-op, so a repeat is planner noise.
# Excludes tools whose repeats are meaningful (calculate, map_values, add_column with
# different targets are already distinguished by their params).
_IDEMPOTENT_ON_REPEAT = frozenset(
    {
        "layout.extract",
        "layout.stack",
        "transform.rename",
        "transform.type_cast",
        "transform.format",
        "transform.add_column",
        "transform.apply_column_rules",
        "transform.reorder_columns",
        "transform.sort_rows",
        "transform.drop_columns",
        "transform.fill_merged",
        "transform.filter_summaries",
        "transform.filter_empty",
        "transform.deduplicate",
        "transform.aggregate_weekly",
        "transform.expand_period_to_daily",
        "transform.infer_granularity_expand_to_daily",
        "transform.date_range_to_weekly",
        "verify.schema",
    }
)


def _params_fingerprint(params: Any) -> str:
    try:
        return json.dumps(params, sort_keys=True, default=str)
    except (TypeError, ValueError):
        return repr(params)


def dedupe_redundant_tool_calls(
    tool_calls: List[Dict[str, Any]],
) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Drop repeat calls of idempotent tools with identical params.

    The replanner regenerates a whole plan from the grid, so it commonly restates
    steps that the previous plan (or the verifier's suggestions) already contain.
    Executing them again is wasted work and produces confusing "already exists;
    no change" outcomes in the trace.

    Returns ``(kept_calls, notes)``.
    """
    if not tool_calls:
        return list(tool_calls or []), []

    seen: Set[Tuple[str, str]] = set()
    kept: List[Dict[str, Any]] = []
    notes: List[str] = []

    for tc in tool_calls:
        if not isinstance(tc, dict):
            kept.append(tc)
            continue
        normalized, _ = normalize_tool_name(str(tc.get("tool") or "").strip())
        if not normalized or normalized not in _IDEMPOTENT_ON_REPEAT:
            kept.append(tc)
            continue
        key = (normalized, _params_fingerprint(tc.get("params")))
        if key in seen:
            notes.append(f"{normalized} (identical params)")
            continue
        seen.add(key)
        kept.append(tc)

    if notes:
        logger.info("Dropped %s redundant tool call(s): %s", len(notes), "; ".join(notes[:8]))
    return kept, notes


def sort_tool_calls_by_pipeline_stage(tool_calls: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Stable-sort tool calls by nominal pipeline stage (pipeline_catalog.stage_sort_key).

    Preserves planner order within the same stage. Fixes common LLM mistakes such as
    value-standardisation tools before date normalisation.
    """
    from . import pipeline_catalog

    if not tool_calls:
        return tool_calls

    defer_drop = _plan_uses_block_metric_tools(tool_calls)

    def primary_sort_key(tc: Dict[str, Any], orig_index: int) -> Tuple[int, int]:
        if not isinstance(tc, dict):
            return (_TOOL_SORT_UNKNOWN_FALLBACK, orig_index)
        raw = tc.get("tool", "")
        normalized, _ = normalize_tool_name(raw)
        if not normalized:
            return (_TOOL_SORT_UNKNOWN_FALLBACK, orig_index)
        if defer_drop and normalized == "transform.drop_columns":
            return (_TOOL_SORT_DROP_AFTER_BLOCK_METRICS, orig_index)
        if normalized == "transform.filter_summaries":
            return (_TOOL_SORT_FILTER_SUMMARIES_AFTER_EXTRACT, orig_index)
        if normalized == "transform.expand_grouped_block":
            return (_TOOL_SORT_EXPAND_GROUPED_BLOCK, orig_index)
        stage = pipeline_catalog.stage_for_tool(normalized)
        if stage is None:
            return (_TOOL_SORT_UNKNOWN_FALLBACK, orig_index)
        return (pipeline_catalog.stage_sort_key(stage), orig_index)

    indexed = list(enumerate(tool_calls))
    indexed.sort(key=lambda pair: primary_sort_key(pair[1], pair[0]))
    return [tc for _i, tc in indexed]


def _validate_stage_monotonicity(tool_calls: List[Dict]) -> List[str]:
    """
    Warn when consecutive valid tools violate nominal pipeline stage order.

    Uses primary stage sort_keys from pipeline_catalog. Unknown tools are skipped.
    """
    from . import pipeline_catalog

    warnings: List[str] = []
    valid_sequence: List[Tuple[int, str, int]] = []  # (index, tool_name, sort_key)

    for i, tc in enumerate(tool_calls):
        if not isinstance(tc, dict) or tc.get("_valid") is False:
            continue
        raw_name = tc.get("tool", "")
        normalized, _ = normalize_tool_name(raw_name)
        if not normalized:
            continue
        stage = pipeline_catalog.stage_for_tool(normalized)
        if stage is None:
            continue
        sk = pipeline_catalog.stage_sort_key(stage)
        valid_sequence.append((i, normalized, sk))

    for j in range(1, len(valid_sequence)):
        prev_i, prev_name, prev_sk = valid_sequence[j - 1]
        curr_i, curr_name, curr_sk = valid_sequence[j]
        if curr_sk < prev_sk:
            warnings.append(
                "Stage order: "
                f"step {curr_i + 1} `{curr_name}` (pipeline stage sort_key={curr_sk}) "
                f"follows step {prev_i + 1} `{prev_name}` (sort_key={prev_sk}); "
                "nominal pipeline expects non-decreasing stage order except valid layout pre-steps."
            )
    return warnings


def _validate_tool_dependencies(tool_calls: List[Dict]) -> List[str]:
    """
    Validate logical dependencies between tools in a sequence.
    
    Rules:
    1. Extract/Stack must come before reshape, enrichment, or validation tools
    2. header.collapse can only be used on raw grids (before extract/stack)
    3. validate_schema can be a checkpoint; final-output validation is enforced elsewhere
    4. map_values/rename/format need data to exist (after extract/stack)
    5. melt/unpivot require extract or stack to have been done first
    
    Returns:
        List of warning messages for dependency violations
    """
    warnings = []
    
    tool_names = [tc.get("tool", "") for tc in tool_calls if tc.get("_valid", True)]
    
    if not tool_names:
        return warnings
    
    # Categorize tools
    extraction_tools = {"layout.extract", "layout.stack"}
    pre_extraction_tools = {"layout.merge_headers"}
    reshape_tools = {"transform.unpivot", "layout.unpivot_matrix"}
    layout_cleanup_tools = {
        "transform.filter_summaries",
        "transform.fill_merged",
        "transform.unmerge_and_fill",
        "transform.densify",
    }
    enrichment_tools = {"transform.map_values", "transform.type_cast", "transform.format",
                        "transform.calculate", "transform.scale_values",
                        "transform.date_range_to_weekly", "transform.expand_date_range_to_daily",
                        "transform.expand_date_range_to_weekly", "transform.aggregate_weekly",
                        "transform.build_date_from_parts", "transform.expand_period_to_daily",
                        "transform.infer_granularity_expand_to_daily",
                        "transform.allocate_block_metric",
                        "transform.classify_metric_level",
                        "transform.infer_block_boundary_columns"}
    validation_tools = {"verify.schema", "validate.cross_source_union"}
    
    has_extraction = any(t in extraction_tools for t in tool_names)
    
    for i, tool_name in enumerate(tool_names):
        # Rule 1: Reshape tools need extraction first
        if tool_name in reshape_tools and not has_extraction:
            earlier = tool_names[:i]
            if not any(t in extraction_tools for t in earlier):
                warnings.append(
                    f"Dependency: '{tool_name}' at step {i+1} requires extract/stack first"
                )
        
        # Rule 2: header.collapse must be before extract/stack
        if tool_name in pre_extraction_tools:
            later = tool_names[i+1:]
            if not any(t in extraction_tools for t in later) and has_extraction:
                # collapse is after extraction — this corrupts data
                earlier = tool_names[:i]
                if any(t in extraction_tools for t in earlier):
                    warnings.append(
                        f"Dependency: '{tool_name}' at step {i+1} should be BEFORE extract/stack, "
                        f"not after — using it post-extraction corrupts data"
                    )
        
        # Rule 3: verify.schema is allowed as a source-level checkpoint.
        # The pipeline can still run post-verify work (multi-source collation,
        # deferred grain tools, final layout) before the final output is complete.
        
        # Rule 4: Enrichment / layout cleanup tools need data (after extract/stack)
        if tool_name in enrichment_tools | layout_cleanup_tools and has_extraction:
            earlier = tool_names[:i]
            if not any(t in extraction_tools for t in earlier):
                warnings.append(
                    f"Dependency: '{tool_name}' at step {i+1} operates on data — "
                    f"ensure extract/stack runs first"
                )

        # Rule 5: Summary filter before rename / block metric tools (flat-table cleanup)
        if tool_name in (
            "transform.rename",
            "transform.type_cast",
            "transform.expand_grouped_block",
            "transform.allocate_block_metric",
            "transform.classify_metric_level",
        ):
            earlier = tool_names[:i]
            if has_extraction and "transform.filter_summaries" not in earlier:
                warnings.append(
                    f"Dependency: '{tool_name}' at step {i+1} should run after "
                    f"transform.filter_summaries when the sheet may contain Total/Subtotal rows"
                )
    
    return warnings


def is_destructive_tool(tool_name: str) -> bool:
    """Check if a tool is marked as destructive (requires HITL confirmation)."""
    normalized, _ = normalize_tool_name(tool_name)
    if normalized in TOOL_SCHEMAS:
        return TOOL_SCHEMAS[normalized].destructive
    return False


def get_destructive_tools(tool_calls: List[Dict]) -> List[str]:
    """Get list of destructive tools in a tool call sequence."""
    destructive = []
    for tc in tool_calls:
        tool_name = tc.get("tool", "")
        if is_destructive_tool(tool_name):
            destructive.append(tool_name)
    return list(set(destructive))
